[project]
name = "flood-based-multicasting-simulation"
version = "0.1.0"
description = "An illustrative simulation for the flood-based multicasting technique"
readme = "README.md"
requires-python = ">=3.11"
dependencies = []
